# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ohzCpshEATGjM0EgVLPPylPT1ExPvs7T
"""
import streamlit as st
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Konfigurasi halaman
st.set_page_config(
    page_title="Movie Recommendation System",
    page_icon="🎬",
    layout="wide"
)

# Load data (cache agar tidak reload setiap kali)
@st.cache_data
def load_movies_data():
    # Ganti baris ini
    df1 = pd.read_csv("movies.csv")  # Hapus sep=";"
    df1['genres'] = df1['genres'].fillna("")
    df1['genres'] = df1['genres'].str.split('|')
    df1['title'] = df1['title'].apply(lambda x: re.sub("[^a-zA-Z0-9 ]", "", x))
    df1 = df1[~df1['genres'].apply(lambda x: '(no genres listed)' in x)]
    return df1

@st.cache_data
def load_ratings_data():
    # Ganti baris ini
    df2 = pd.read_csv("ratings.csv")  # Hapus sep=";"
    return df2.drop(['timestamp'], axis=1)

@st.cache_data
def prepare_vectors(movies_data):
    vectorizer_title = TfidfVectorizer(ngram_range=(1,2))
    tfidf_title = vectorizer_title.fit_transform(movies_data['title'])
    movies_data['genres_text'] = movies_data['genres'].apply(lambda x: ' '.join(x))
    vectorizer_genres = TfidfVectorizer(ngram_range=(1,2))
    tfidf_genres = vectorizer_genres.fit_transform(movies_data['genres_text'])
    return vectorizer_title, tfidf_title, vectorizer_genres, tfidf_genres

# Load data
movies_data = load_movies_data()
ratings_data = load_ratings_data()
combined_data = ratings_data.merge(movies_data, on='movieId')

# Vektorisasi
vectorizer_title, tfidf_title, vectorizer_genres, tfidf_genres = prepare_vectors(movies_data)

# Daftar genre unik untuk filter
all_genres = sorted(movies_data['genres'].explode().unique())
all_genres = [g for g in all_genres if g and g != '']

# Fungsi rekomendasi
def clean_title(title):
    return re.sub("[^a-zA-Z0-9 ]", "", title)

def search_by_title(title):
    title = clean_title(title)
    query_vec = vectorizer_title.transform([title])
    similarity = cosine_similarity(query_vec, tfidf_title).flatten()
    indices = np.argpartition(similarity, -5)[-5:]
    return movies_data.iloc[indices][::-1]

def search_similar_genres(genres):
    query_vec = vectorizer_genres.transform([genres])
    similarity = cosine_similarity(query_vec, tfidf_genres).flatten()
    indices = np.argpartition(similarity, -10)[-10:]
    return movies_data.iloc[indices][::-1]

def scores_calculator(movie_id):
    similar_users = combined_data.loc[
        (combined_data['movieId'] == movie_id) & (combined_data['rating'] >= 4), 'userId'
    ].unique()
    similar_user_recs = combined_data.loc[
        (combined_data['userId'].isin(similar_users)) & (combined_data['rating'] >= 4), 'movieId'
    ].value_counts(normalize=True)
    all_user_recs = combined_data.loc[
        combined_data['movieId'].isin(similar_user_recs.index) & (combined_data['rating'] >= 4)
    ]['movieId'].value_counts(normalize=True)
    selected_genres = combined_data.loc[combined_data['movieId'] == movie_id, 'genres'].iloc[0]
    if isinstance(selected_genres, list):
        selected_genres = " ".join(selected_genres)
    similar_genre_ids = search_similar_genres(selected_genres)['movieId']
    similar_user_recs.loc[similar_user_recs.index.isin(similar_genre_ids)] *= 1.5
    all_user_recs.loc[all_user_recs.index.isin(similar_genre_ids)] *= 0.9
    scores = pd.DataFrame({
        'similar': similar_user_recs,
        'all': all_user_recs
    }).fillna(0)
    scores['score'] = np.where(scores['all'] > 0, scores['similar'] / scores['all'], 0)
    return scores.sort_values('score', ascending=False)

def recommendation_results(user_input, title_idx=0, genre_filter=None):
    title_candidates = search_by_title(user_input)
    movie_id = title_candidates.iloc[title_idx]['movieId']
    scores = scores_calculator(movie_id)
    results = scores.head(30).merge(movies_data, left_index=True, right_on='movieId')[['movieId', 'title', 'score', 'genres']]

    # Filter berdasarkan genre
    if genre_filter and len(genre_filter) > 0:
        results = results[results['genres'].apply(lambda x: any(g in x for g in genre_filter))]

    return results.head(10)

# Fungsi untuk mendapatkan film berdasarkan genre
def get_movies_by_genre(genres, limit=20):
    filtered = movies_data.copy()
    for genre in genres:
        filtered = filtered[filtered['genres'].apply(lambda x: genre in x)]
    return filtered.head(limit)

# ==================== SIDEBAR ====================
st.sidebar.title("🎬 Movie Recommender")
st.sidebar.markdown("---")
page = st.sidebar.radio("Navigate to:", ["🏠 Home", "📊 Data Analysis", "🎯 Recommendation", "🎭 Browse by Genre"])

# ==================== HOME PAGE ====================
if page == "🏠 Home":
    st.title("🎥 Movie Recommendation System")
    st.markdown("""
    Welcome to the **Movie Recommendation System**!
    This app uses **Collaborative Filtering** and **Content-Based Filtering** to suggest movies you might like.

    ### Features:
    - 📊 **Data Analysis**: Explore movie genres, ratings distribution, and top movies.
    - 🎯 **Recommendation**: Get personalized movie recommendations based on your input.
    - 🎭 **Browse by Genre**: Filter and explore movies by genre.
    """)

    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Total Movies", f"{len(movies_data):,}")
    with col2:
        st.metric("Total Ratings", f"{len(ratings_data):,}")
    with col3:
        st.metric("Unique Genres", f"{len(all_genres)}")

# ==================== DATA ANALYSIS PAGE ====================
elif page == "📊 Data Analysis":
    st.title("📊 Movie Data Analysis")

    # Sidebar filter untuk analisis
    with st.sidebar:
        st.markdown("### 🔍 Filter Analysis")
        selected_analysis_genres = st.multiselect(
            "Filter by Genre (Optional):",
            options=all_genres,
            default=[]
        )

    tab1, tab2, tab3 = st.tabs(["🎭 Genre Distribution", "⭐ Rating Distribution", "🏆 Top Movies"])

    with tab1:
        st.subheader("Number of Movies per Genre")

        # Data genre counts
        genre_counts = pd.Series([genre for genres_list in movies_data['genres'] for genre in genres_list]).value_counts()

        # Filter jika ada genre yang dipilih
        if selected_analysis_genres:
            genre_counts = genre_counts[genre_counts.index.isin(selected_analysis_genres)]

        fig, ax = plt.subplots(figsize=(12, 6))
        genre_counts.plot(kind='bar', color='skyblue', ax=ax)
        ax.set_title("Jumlah Film per Genre", fontsize=16)
        ax.set_xlabel("Genre")
        ax.set_ylabel("Jumlah Film")
        plt.xticks(rotation=45, ha='right')
        st.pyplot(fig)

    with tab2:
        st.subheader("Rating Distribution")
        fig, ax = plt.subplots(figsize=(8, 6))
        sns.histplot(ratings_data['rating'], bins=10, kde=False, color='skyblue', ax=ax)
        ax.set_title("Distribusi Rating", fontsize=16)
        ax.set_xlabel("Rating")
        ax.set_ylabel("Frekuensi")
        st.pyplot(fig)

        # Statistik rating
        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("Average Rating", f"{ratings_data['rating'].mean():.2f}")
        with col2:
            st.metric("Most Common Rating", f"{ratings_data['rating'].mode()[0]}")
        with col3:
            st.metric("Total Ratings", f"{len(ratings_data):,}")

    with tab3:
        st.subheader("Top 10 Movies by Average Rating")
        avg_ratings = combined_data.groupby('title')['rating'].mean().sort_values(ascending=False).head(10)
        st.dataframe(avg_ratings.reset_index().rename(columns={'title': 'Movie', 'rating': 'Avg Rating'}), use_container_width=True)

        st.subheader("Top 10 Most Rated Movies")
        most_rated = combined_data.groupby('title')['rating'].count().sort_values(ascending=False).head(10)
        st.dataframe(most_rated.reset_index().rename(columns={'title': 'Movie', 'rating': 'Rating Count'}), use_container_width=True)

# ==================== RECOMMENDATION PAGE ====================
elif page == "🎯 Recommendation":
    st.title("🎯 Get Movie Recommendations")

    # Filter genre di sidebar
    with st.sidebar:
        st.markdown("### 🎭 Filter Recommendations")
        selected_genres_filter = st.multiselect(
            "Filter recommendations by genre:",
            options=all_genres,
            default=[],
            help="Select genres to filter recommended movies"
        )

    col1, col2 = st.columns([3, 1])
    with col1:
        user_input = st.text_input("Enter a movie title:", "Jumanji")
    with col2:
        st.write("")
        st.write("")
        search_btn = st.button("🔍 Search", use_container_width=True)

    if search_btn or user_input:
        st.subheader("🔎 Did you mean?")
        candidates = search_by_title(user_input)
        title_options = candidates['title'].tolist()
        selected_title = st.selectbox("Select the correct movie:", title_options)

        if st.button("🎬 Get Recommendations", type="primary", use_container_width=True):
            idx = title_options.index(selected_title)

            with st.spinner("Finding recommendations for you..."):
                recommendations = recommendation_results(user_input, idx, selected_genres_filter)

            if len(recommendations) == 0:
                st.warning("No movies found with the selected genre filters. Try removing some filters.")
            else:
                st.subheader("🎥 Recommended Movies for You")

                # Tampilkan filter yang aktif
                if selected_genres_filter:
                    st.info(f"📌 Filtering by genres: {', '.join(selected_genres_filter)}")

                # Tampilkan rekomendasi dalam grid
                cols = st.columns(2)
                for i, (_, row) in enumerate(recommendations.iterrows()):
                    with cols[i % 2]:
                        with st.container(border=True):
                            st.markdown(f"**🎬 {row['title']}**")
                            st.caption(f"🏷️ **Genres:** {', '.join(row['genres'])}")
                            st.progress(min(row['score'] / 10, 1.0), text=f"⭐ Score: {row['score']:.2f}")
                            st.divider()

# ==================== BROWSE BY GENRE PAGE ====================
elif page == "🎭 Browse by Genre":
    st.title("🎭 Browse Movies by Genre")

    # Multi-select untuk genre
    with st.sidebar:
        st.markdown("### 🎭 Genre Selection")
        browse_genres = st.multiselect(
            "Select one or more genres:",
            options=all_genres,
            default=["Comedy"] if "Comedy" in all_genres else [],
            help="Select genres to filter movies"
        )

        st.markdown("### ⚙️ Display Options")
        num_movies = st.slider("Number of movies to show:", min_value=5, max_value=50, value=20)
        sort_by = st.selectbox("Sort by:", ["Rating (Highest)", "Rating (Lowest)", "Title (A-Z)", "Title (Z-A)"])

    if browse_genres:
        st.subheader(f"📽️ Movies in: {', '.join(browse_genres)}")

        # Filter movies by selected genres
        filtered_movies = movies_data.copy()
        for genre in browse_genres:
            filtered_movies = filtered_movies[filtered_movies['genres'].apply(lambda x: genre in x)]

        # Tambahkan rating rata-rata
        avg_ratings = combined_data.groupby('movieId')['rating'].mean().reset_index()
        filtered_movies = filtered_movies.merge(avg_ratings, on='movieId', how='left')
        filtered_movies = filtered_movies.rename(columns={'rating': 'avg_rating'})

        # Urutkan
        if sort_by == "Rating (Highest)":
            filtered_movies = filtered_movies.sort_values('avg_rating', ascending=False)
        elif sort_by == "Rating (Lowest)":
            filtered_movies = filtered_movies.sort_values('avg_rating', ascending=True)
        elif sort_by == "Title (A-Z)":
            filtered_movies = filtered_movies.sort_values('title', ascending=True)
        elif sort_by == "Title (Z-A)":
            filtered_movies = filtered_movies.sort_values('title', ascending=False)

        filtered_movies = filtered_movies.head(num_movies)

        if len(filtered_movies) == 0:
            st.warning("No movies found with the selected genres.")
        else:
            st.caption(f"Found {len(filtered_movies)} movies")

            # Tampilkan dalam grid
            cols = st.columns(3)
            for i, (_, row) in enumerate(filtered_movies.iterrows()):
                with cols[i % 3]:
                    with st.container(border=True):
                        st.markdown(f"**{row['title']}**")
                        st.caption(f"🏷️ **Genres:** {', '.join(row['genres'])}")
                        if pd.notna(row['avg_rating']):
                            st.caption(f"⭐ **Avg Rating:** {row['avg_rating']:.2f}/5.0")
                        else:
                            st.caption("⭐ **Avg Rating:** No ratings yet")
    else:
        st.info("👈 Please select at least one genre from the sidebar to browse movies.")

        # Tampilkan genre populer
        st.subheader("🔥 Popular Genres")
        genre_counts = pd.Series([genre for genres_list in movies_data['genres'] for genre in genres_list]).value_counts().head(12)

        cols = st.columns(4)
        for i, (genre, count) in enumerate(genre_counts.items()):
            with cols[i % 4]:
                st.markdown(f"**{genre}**")
                st.caption(f"{count:,} movies")
