# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ohzCpshEATGjM0EgVLPPylPT1ExPvs7T
"""
import streamlit as st
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns
import requests
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Konfigurasi halaman
st.set_page_config(
    page_title="Movie Recommendation System",
    page_icon="🎬",
    layout="wide"
)

# ==================== LOAD DATA ====================
@st.cache_data
def load_movies_data():
    df1 = pd.read_csv("movies.csv")
    df1['genres'] = df1['genres'].fillna("")
    df1['genres'] = df1['genres'].str.split('|')
    df1['title'] = df1['title'].apply(lambda x: re.sub("[^a-zA-Z0-9 ]", "", x))
    df1 = df1[~df1['genres'].apply(lambda x: '(no genres listed)' in x)]
    return df1

@st.cache_data
def load_ratings_data():
    df2 = pd.read_csv("ratings.csv")
    return df2.drop(['timestamp'], axis=1)

@st.cache_data
def prepare_vectors(movies_data):
    vectorizer_title = TfidfVectorizer(ngram_range=(1,2))
    tfidf_title = vectorizer_title.fit_transform(movies_data['title'])
    movies_data['genres_text'] = movies_data['genres'].apply(lambda x: ' '.join(x))
    vectorizer_genres = TfidfVectorizer(ngram_range=(1,2))
    tfidf_genres = vectorizer_genres.fit_transform(movies_data['genres_text'])
    return vectorizer_title, tfidf_title, vectorizer_genres, tfidf_genres

# ==================== FUNGSI POSTER TMDB ====================
@st.cache_data(show_spinner=False)
def fetch_movie_poster(movie_title):
    try:
        API_KEY = st.secrets.get("TMDB_API_KEY", "")
        if not API_KEY:
            return None
        
        import urllib.parse
        clean_title_for_search = urllib.parse.quote(movie_title)
        search_url = f"https://api.themoviedb.org/3/search/movie?api_key={API_KEY}&query={clean_title_for_search}"
        
        response = requests.get(search_url, timeout=10)
        
        if response.status_code == 401:
            return None
        
        data = response.json()
        
        if data['results']:
            poster_path = data['results'][0].get('poster_path')
            if poster_path:
                return f"https://image.tmdb.org/t/p/w500{poster_path}"
        return None
    except Exception:
        return None

# ==================== LOAD DAN PROSES DATA ====================
movies_data = load_movies_data()
ratings_data = load_ratings_data()
combined_data = ratings_data.merge(movies_data, on='movieId')

# Vektorisasi
vectorizer_title, tfidf_title, vectorizer_genres, tfidf_genres = prepare_vectors(movies_data)

# Daftar genre unik untuk filter
all_genres = sorted(movies_data['genres'].explode().unique())
all_genres = [g for g in all_genres if g and g != '']

# ==================== FUNGSI REKOMENDASI ====================
def clean_title(title):
    return re.sub("[^a-zA-Z0-9 ]", "", title)

def search_by_title(title):
    title = clean_title(title)
    query_vec = vectorizer_title.transform([title])
    similarity = cosine_similarity(query_vec, tfidf_title).flatten()
    indices = np.argpartition(similarity, -5)[-5:]
    return movies_data.iloc[indices][::-1]

def search_similar_genres(genres):
    query_vec = vectorizer_genres.transform([genres])
    similarity = cosine_similarity(query_vec, tfidf_genres).flatten()
    indices = np.argpartition(similarity, -10)[-10:]
    return movies_data.iloc[indices][::-1]

def scores_calculator(movie_id):
    # Cek apakah movie_id ada di combined_data
    if movie_id not in combined_data['movieId'].values:
        return pd.DataFrame(columns=['similar', 'all', 'score'])
    
    similar_users = combined_data.loc[
        (combined_data['movieId'] == movie_id) & (combined_data['rating'] >= 4), 'userId'
    ].unique()
    
    if len(similar_users) == 0:
        return pd.DataFrame(columns=['similar', 'all', 'score'])
    
    similar_user_recs = combined_data.loc[
        (combined_data['userId'].isin(similar_users)) & (combined_data['rating'] >= 4), 'movieId'
    ].value_counts(normalize=True)
    
    all_user_recs = combined_data.loc[
        combined_data['movieId'].isin(similar_user_recs.index) & (combined_data['rating'] >= 4)
    ]['movieId'].value_counts(normalize=True)
    
    # Cek apakah movie_id ada di combined_data untuk mengambil genres
    movie_data = combined_data.loc[combined_data['movieId'] == movie_id]
    if len(movie_data) == 0:
        return pd.DataFrame(columns=['similar', 'all', 'score'])
    
    selected_genres = movie_data['genres'].iloc[0]
    if isinstance(selected_genres, list):
        selected_genres = " ".join(selected_genres)
    
    similar_genre_ids = search_similar_genres(selected_genres)['movieId']
    similar_user_recs.loc[similar_user_recs.index.isin(similar_genre_ids)] *= 1.5
    all_user_recs.loc[all_user_recs.index.isin(similar_genre_ids)] *= 0.9
    
    scores = pd.DataFrame({
        'similar': similar_user_recs,
        'all': all_user_recs
    }).fillna(0)
    scores['score'] = np.where(scores['all'] > 0, scores['similar'] / scores['all'], 0)
    return scores.sort_values('score', ascending=False)

def recommendation_results(user_input, title_idx=0, genre_filter=None):
    title_candidates = search_by_title(user_input)
    
    if len(title_candidates) == 0:
        return pd.DataFrame(columns=['title', 'score', 'genres'])
    
    movie_id = title_candidates.iloc[title_idx]['movieId']
    scores = scores_calculator(movie_id)
    
    if len(scores) == 0:
        return pd.DataFrame(columns=['title', 'score', 'genres'])
    
    results = scores.head(30).merge(movies_data, left_index=True, right_on='movieId')[['movieId', 'title', 'score', 'genres']]
    
    if genre_filter and len(genre_filter) > 0:
        results = results[results['genres'].apply(lambda x: any(g in x for g in genre_filter))]
    
    return results.head(10)

# ==================== SIDEBAR NAVIGASI ====================
st.sidebar.title("🎬 Movie Recommender")
st.sidebar.markdown("---")
page = st.sidebar.radio("Navigate to:", ["🏠 Home", "📊 Data Analysis", "🎯 Recommendation", "🎭 Browse by Genre"])

# ==================== HOME PAGE ====================
if page == "🏠 Home":
    st.title("🎥 Movie Recommendation System")
    st.markdown("""
    Welcome to the **Movie Recommendation System**!  
    This app uses **Collaborative Filtering** and **Content-Based Filtering** to suggest movies you might like.
    """)
    
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("Total Movies", f"{len(movies_data):,}")
    with col2:
        st.metric("Total Ratings", f"{len(ratings_data):,}")
    with col3:
        st.metric("Unique Genres", f"{len(all_genres)}")

# ==================== DATA ANALYSIS PAGE ====================
elif page == "📊 Data Analysis":
    st.title("📊 Movie Data Analysis")
    
    tab1, tab2 = st.tabs(["🎭 Genre Distribution", "⭐ Rating Distribution"])
    
    with tab1:
        st.subheader("Number of Movies per Genre")
        genre_counts = pd.Series([genre for genres_list in movies_data['genres'] for genre in genres_list]).value_counts()
        fig, ax = plt.subplots(figsize=(12, 6))
        genre_counts.plot(kind='bar', color='skyblue', ax=ax)
        ax.set_title("Jumlah Film per Genre", fontsize=16)
        ax.set_xlabel("Genre")
        ax.set_ylabel("Jumlah Film")
        plt.xticks(rotation=45, ha='right')
        st.pyplot(fig)
    
    with tab2:
        st.subheader("Rating Distribution")
        fig, ax = plt.subplots(figsize=(8, 6))
        sns.histplot(ratings_data['rating'], bins=10, kde=False, color='skyblue', ax=ax)
        ax.set_title("Distribusi Rating", fontsize=16)
        ax.set_xlabel("Rating")
        ax.set_ylabel("Frekuensi")
        st.pyplot(fig)

# ==================== RECOMMENDATION PAGE ====================
elif page == "🎯 Recommendation":
    st.title("🎯 Get Movie Recommendations")
    
    with st.sidebar:
        st.markdown("### 🎭 Filter Recommendations")
        selected_genres_filter = st.multiselect(
            "Filter recommendations by genre:",
            options=all_genres,
            default=[]
        )
    
    col1, col2 = st.columns([3, 1])
    with col1:
        user_input = st.text_input("Enter a movie title:", "Jumanji")
    with col2:
        st.write("")
        st.write("")
        search_btn = st.button("🔍 Search", use_container_width=True)
    
    if search_btn or user_input:
        st.subheader("🔎 Did you mean?")
        candidates = search_by_title(user_input)
        
        if len(candidates) == 0:
            st.warning(f"No movie found with title '{user_input}'. Please try another title.")
        else:
            title_options = candidates['title'].tolist()
            selected_title = st.selectbox("Select the correct movie:", title_options)
            
            if st.button("🎬 Get Recommendations", type="primary", use_container_width=True):
                idx = title_options.index(selected_title)
                
                with st.spinner("Finding recommendations for you..."):
                    recommendations = recommendation_results(user_input, idx, selected_genres_filter)
                
                if len(recommendations) == 0:
                    st.warning("No recommendations found. Try a different movie or remove genre filters.")
                else:
                    st.subheader("🎥 Recommended Movies for You")
                    
                    if selected_genres_filter:
                        st.info(f"📌 Filtering by genres: {', '.join(selected_genres_filter)}")
                    
                    for _, row in recommendations.iterrows():
                        col_img, col_text = st.columns([1, 3])
                        
                        with col_img:
                            poster_url = fetch_movie_poster(row['title'])
                            if poster_url:
                                st.image(poster_url, use_container_width=True)
                            else:
                                st.markdown(
                                    f"""
                                    <div style="background-color: #f0f2f6; 
                                                height: 200px; 
                                                display: flex; 
                                                align-items: center; 
                                                justify-content: center; 
                                                border-radius: 10px;
                                                text-align: center;">
                                        <span style="color: #666;">🎬<br>No Poster</span>
                                    </div>
                                    """, 
                                    unsafe_allow_html=True
                                )
                        
                        with col_text:
                            st.markdown(f"**🎬 {row['title']}**")
                            st.caption(f"🏷️ **Genres:** {', '.join(row['genres'])}")
                            st.progress(min(row['score'] / 10, 1.0), text=f"⭐ Score: {row['score']:.2f}")
                        
                        st.divider()

# ==================== BROWSE BY GENRE PAGE ====================
elif page == "🎭 Browse by Genre":
    st.title("🎭 Browse Movies by Genre")
    
    with st.sidebar:
        st.markdown("### 🎭 Genre Selection")
        browse_genres = st.multiselect(
            "Select one or more genres:",
            options=all_genres,
            default=["Comedy"] if "Comedy" in all_genres else []
        )
        
        st.markdown("### ⚙️ Display Options")
        num_movies = st.slider("Number of movies to show:", min_value=5, max_value=50, value=20)
        sort_by = st.selectbox("Sort by:", ["Rating (Highest)", "Rating (Lowest)", "Title (A-Z)", "Title (Z-A)"])
    
    if browse_genres:
        st.subheader(f"📽️ Movies in: {', '.join(browse_genres)}")
        
        filtered_movies = movies_data.copy()
        for genre in browse_genres:
            filtered_movies = filtered_movies[filtered_movies['genres'].apply(lambda x: genre in x)]
        
        avg_ratings = combined_data.groupby('movieId')['rating'].mean().reset_index()
        filtered_movies = filtered_movies.merge(avg_ratings, on='movieId', how='left')
        filtered_movies = filtered_movies.rename(columns={'rating': 'avg_rating'})
        
        if sort_by == "Rating (Highest)":
            filtered_movies = filtered_movies.sort_values('avg_rating', ascending=False)
        elif sort_by == "Rating (Lowest)":
            filtered_movies = filtered_movies.sort_values('avg_rating', ascending=True)
        elif sort_by == "Title (A-Z)":
            filtered_movies = filtered_movies.sort_values('title', ascending=True)
        elif sort_by == "Title (Z-A)":
            filtered_movies = filtered_movies.sort_values('title', ascending=False)
        
        filtered_movies = filtered_movies.head(num_movies)
        
        if len(filtered_movies) == 0:
            st.warning("No movies found with the selected genres.")
        else:
            st.caption(f"Found {len(filtered_movies)} movies")
            
            cols = st.columns(3)
            for i, (_, row) in enumerate(filtered_movies.iterrows()):
                with cols[i % 3]:
                    with st.container(border=True):
                        st.markdown(f"**{row['title']}**")
                        st.caption(f"🏷️ **Genres:** {', '.join(row['genres'])}")
                        if pd.notna(row['avg_rating']):
                            st.caption(f"⭐ **Avg Rating:** {row['avg_rating']:.2f}/5.0")
                        else:
                            st.caption("⭐ **Avg Rating:** No ratings yet")
    else:
        st.info("👈 Please select at least one genre from the sidebar to browse movies.")
        
        st.subheader("🔥 Popular Genres")
        genre_counts = pd.Series([genre for genres_list in movies_data['genres'] for genre in genres_list]).value_counts().head(12)
        
        cols = st.columns(4)
        for i, (genre, count) in enumerate(genre_counts.items()):
            with cols[i % 4]:
                st.markdown(f"**{genre}**")
                st.caption(f"{count:,} movies")
